<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="HotChocolate.AspNetCore" Version="13.8.1" />
	  <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\Shared.Implementations\Shared.Implementations.csproj" />
    <ProjectReference Include="..\DataProcessorService.Application\DataProcessorService.Application.csproj" />
    <ProjectReference Include="..\DataProcessorService.Infrastructure\DataProcessorService.Infrastructure.csproj" />
  </ItemGroup>

</Project>
